# Libraries and loading the dataset
In this first part of the examples we provide we will look at how to load in the dataset, and how to do some basic
manipulation of the data. In order to run the code in this notebook you will need to install, besides Jupyter, the
[Pandas](https://pandas.pydata.org/docs/getting_started/index.html#installation) package.

For more info on how to set up the Python environment for these notebooks, see README.md.

## Getting an overview of the data
Whenever you get a dataset you will want to inspect it and see what variables (columns) you have and what these values
look like. One way of doing this is to use the package [Pandas](https://pandas.pydata.org/docs/getting_started/overview.html),
a package that allows for easy manipulation of the data table (or dataframe, as it is called in Pandas).

For a quick overview of Pandas' capabilities, check out [this](https://pandas.pydata.org/docs/user_guide/10min.html#min)
link.

In [106]:
import pandas as pd
owid_data = pd.read_csv(r"../data/owid-covid-data.csv")
cgrt_data = pd.read_csv(r"../data/OxCGRT_latest_combined.csv", low_memory=False)

cgrt_data.head()

,CountryName,CountryCode,RegionName,RegionCode,Jurisdiction,Date,C1_combined_numeric,C1_combined,C2_combined_numeric,C2_combined,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200101,0.0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200102,0.0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200103,0.0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200104,0.0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,NAT_TOTAL,20200105,0.0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In the above output table you can see the indices of the columns (using standard 0-indexing) as well as the human-readable
name and information about what the data in those columns is. For example: at index 0 we find the `iso_index` this is a
shorthand code for countries (see [here](https://www.iso.org/obp/ui/#search/code/)).

We can also see that there are 83862 'non-nullable' rows for that column. This means non-empty cells in that column. Since
dataframes can be sparsely populated, some rows can have empty column values (e.g. a row can miss the value for `new_tests`
but still have other values).

Lastly, we can see the Python data type for that column. Most will either be floating point numbers or unnamed objects -
meaning they contain multiple values within a single data point.

Note that, in this example, we're only loading in a single dataset. We provided several for you to analyse. Please check
the `data` directory for more data files.

## Fixing the date column
We can see that `date` column is not of the `datetime` object type, a commonly used format for timestamps in Python. It
will be useful to use this column as the x-axis for various plots and analyses, but most of those techniques assume that
the timestamps are in the aforementioned `datetime` format.

This means that if we want to use the `date` column effectively, we will have to alter the data type to `datetime`. The
following code block will show you how to do that. It is recommended to do this for your own analysis too!

In [109]:
owid_data['dateFixed'] = pd.to_datetime(owid_data['date'], format = '%Y-%m-%d')
cgrt_data['dateFixed'] = pd.to_datetime(cgrt_data['Date'], format = '%Y%m%d')
cgrt_data = cgrt_data.rename(columns={"CountryCode":"iso_code"})

KeyError: "None of ['iso_code'] are in the columns"

Your dataset is now ready for your analysis! You may want to sort your data set by date in order to more intuitively see
changes. You can do so doing:

                       CountryName RegionName RegionCode Jurisdiction  \
CountryCode dateFixed
ABW         2020-01-01       Aruba        NaN        NaN    NAT_TOTAL
            2020-01-02       Aruba        NaN        NaN    NAT_TOTAL
            2020-01-03       Aruba        NaN        NaN    NAT_TOTAL
            2020-01-04       Aruba        NaN        NaN    NAT_TOTAL
            2020-01-05       Aruba        NaN        NaN    NAT_TOTAL
...                            ...        ...        ...          ...
ZWE         2021-04-21    Zimbabwe        NaN        NaN    NAT_TOTAL
            2021-04-22    Zimbabwe        NaN        NaN    NAT_TOTAL
            2021-04-23    Zimbabwe        NaN        NaN    NAT_TOTAL
            2021-04-24    Zimbabwe        NaN        NaN    NAT_TOTAL
            2021-04-25    Zimbabwe        NaN        NaN    NAT_TOTAL

                            Date  C1_combined_numeric C1_combined  \
CountryCode dateFixed
ABW         2020-01-01  20200101                  0.0           0
            2020-01-02  20200102                  0.0           0
            2020-01-03  20200103                  0.0           0
            2020-01-04  20200104                  0.0           0
            2020-01-05  20200105                  0.0           0
...                          ...                  ...         ...
ZWE         2021-04-21  20210421                  1.0          1G
            2021-04-22  20210422                  1.0          1G
            2021-04-23  20210423                  1.0          1G
            2021-04-24  20210424                  1.0          1G
            2021-04-25  20210425                  1.0          1G

                        C2_combined_numeric C2_combined  C3_combined_numeric  \
CountryCode dateFixed
ABW         2020-01-01                  0.0           0                  0.0
            2020-01-02                  0.0           0                  0.0
            2020-01-03                  0.0           0                  0.0
            2020-01-04                  0.0           0                  0.0
            2020-01-05                  0.0           0                  0.0
...                                     ...         ...                  ...
ZWE         2021-04-21                  2.0          2G                  2.0
            2021-04-22                  2.0          2G                  2.0
            2021-04-23                  2.0          2G                  2.0
            2021-04-24                  2.0          2G                  2.0
            2021-04-25                  NaN         NaN                  2.0

                        ... StringencyIndex  StringencyIndexForDisplay  \
CountryCode dateFixed   ...
ABW         2020-01-01  ...            0.00                       0.00
            2020-01-02  ...            0.00                       0.00
            2020-01-03  ...            0.00                       0.00
            2020-01-04  ...            0.00                       0.00
            2020-01-05  ...            0.00                       0.00
...                     ...             ...                        ...
ZWE         2021-04-21  ...           51.85                      51.85
            2021-04-22  ...           51.85                      51.85
            2021-04-23  ...           51.85                      51.85
            2021-04-24  ...           51.85                      51.85
            2021-04-25  ...             NaN                      51.85

                       StringencyLegacyIndex  StringencyLegacyIndexForDisplay  \
CountryCode dateFixed
ABW         2020-01-01                  0.00                             0.00
            2020-01-02                  0.00                             0.00
            2020-01-03                  0.00                             0.00
            2020-01-04                  0.00                             0.00
            2020-01-05                  0.00                             0.00
...                                      ...                              ...
ZWE         2021-04-21                 60.71                            60.71
            2021-04-22                 60.71                            60.71
            2021-04-23                 60.71                            60.71
            2021-04-24                 60.71                            60.71
            2021-04-25                   NaN                            60.71

                       GovernmentResponseIndex  \
CountryCode dateFixed
ABW         2020-01-01                    0.00
            2020-01-02                    0.00
            2020-01-03                    0.00
            2020-01-04                    0.00
            2020-01-05                    0.00
...                                        ...
ZWE         2021-04-21                   49.27
            2021-04-22                   49.27
            2021-04-23                   49.27
            2021-04-24                   49.27
            2021-04-25                     NaN

                        GovernmentResponseIndexForDisplay  \
CountryCode dateFixed
ABW         2020-01-01                               0.00
            2020-01-02                               0.00
            2020-01-03                               0.00
            2020-01-04                               0.00
            2020-01-05                               0.00
...                                                   ...
ZWE         2021-04-21                              49.27
            2021-04-22                              49.27
            2021-04-23                              49.27
            2021-04-24                              49.27
            2021-04-25                              49.27

                       ContainmentHealthIndex  \
CountryCode dateFixed
ABW         2020-01-01                   0.00
            2020-01-02                   0.00
            2020-01-03                   0.00
            2020-01-04                   0.00
            2020-01-05                   0.00
...                                       ...
ZWE         2021-04-21                  56.31
            2021-04-22                  56.31
            2021-04-23                  56.31
            2021-04-24                  56.31
            2021-04-25                    NaN

                        ContainmentHealthIndexForDisplay EconomicSupportIndex  \
CountryCode dateFixed
ABW         2020-01-01                              0.00                  0.0
            2020-01-02                              0.00                  0.0
            2020-01-03                              0.00                  0.0
            2020-01-04                              0.00                  0.0
            2020-01-05                              0.00                  0.0
...                                                  ...                  ...
ZWE         2021-04-21                             56.31                  0.0
            2021-04-22                             56.31                  0.0
            2021-04-23                             56.31                  0.0
            2021-04-24                             56.31                  0.0
            2021-04-25                             56.31                  0.0

                        EconomicSupportIndexForDisplay
CountryCode dateFixed
ABW         2020-01-01                             0.0
            2020-01-02                             0.0
            2020-01-03                             0.0
            2020-01-04                             0.0
            2020-01-05                             0.0
...                                                ...
ZWE         2021-04-21                             0.0
            2021-04-22                             0.0
            2021-04-23                             0.0
            2021-04-24                             0.0
            2021-04-25                             0.0

[135161 rows x 49 columns]

In [98]:
full_data = owid_data.merge(cgrt_data, left_index=True, right_index=True)
full_data.head()

                                     continent   location        date  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW          South America  Argentina  2020-01-01
                    AFG          South America  Argentina  2020-01-01
                    AGO          South America  Argentina  2020-01-01
                    ALB          South America  Argentina  2020-01-01
                    AND          South America  Argentina  2020-01-01

                                 total_cases  new_cases  new_cases_smoothed  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                  NaN        NaN                 NaN
                    AFG                  NaN        NaN                 NaN
                    AGO                  NaN        NaN                 NaN
                    ALB                  NaN        NaN                 NaN
                    AND                  NaN        NaN                 NaN

                                 total_deaths  new_deaths  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                   NaN         NaN
                    AFG                   NaN         NaN
                    AGO                   NaN         NaN
                    ALB                   NaN         NaN
                    AND                   NaN         NaN

                                 new_deaths_smoothed  total_cases_per_million  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                          NaN                      NaN
                    AFG                          NaN                      NaN
                    AGO                          NaN                      NaN
                    ALB                          NaN                      NaN
                    AND                          NaN                      NaN

                                 ...  StringencyIndex  \
dateFixed  iso_code CountryCode  ...
2020-01-01 ARG      ABW          ...              0.0
                    AFG          ...              0.0
                    AGO          ...              0.0
                    ALB          ...              0.0
                    AND          ...              0.0

                                 StringencyIndexForDisplay  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                                0.0
                    AFG                                0.0
                    AGO                                0.0
                    ALB                                0.0
                    AND                                0.0

                                 StringencyLegacyIndex  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                            0.0
                    AFG                            0.0
                    AGO                            0.0
                    ALB                            0.0
                    AND                            0.0

                                 StringencyLegacyIndexForDisplay  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                                      0.0
                    AFG                                      0.0
                    AGO                                      0.0
                    ALB                                      0.0
                    AND                                      0.0

                                 GovernmentResponseIndex  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                              0.0
                    AFG                              0.0
                    AGO                              0.0
                    ALB                              0.0
                    AND                              0.0

                                 GovernmentResponseIndexForDisplay  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                                        0.0
                    AFG                                        0.0
                    AGO                                        0.0
                    ALB                                        0.0
                    AND                                        0.0

                                 ContainmentHealthIndex  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                             0.0
                    AFG                             0.0
                    AGO                             0.0
                    ALB                             0.0
                    AND                             0.0

                                 ContainmentHealthIndexForDisplay  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                                       0.0
                    AFG                                       0.0
                    AGO                                       0.0
                    ALB                                       0.0
                    AND                                       0.0

                                 EconomicSupportIndex  \
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                           0.0
                    AFG                           0.0
                    AGO                           0.0
                    ALB                           0.0
                    AND                           0.0

                                 EconomicSupportIndexForDisplay
dateFixed  iso_code CountryCode
2020-01-01 ARG      ABW                                     0.0
                    AFG                                     0.0
                    AGO                                     0.0
                    ALB                                     0.0
                    AND                                     0.0

[5 rows x 107 columns]

In [99]:
full_data.to_csv("../data/full_data.csv")

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-99-594b6143b985>", line 1, in <module>
    full_data.to_csv("../data/full_data.csv")
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\core\generic.py", line 3387, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\io\formats\format.py", line 1083, in to_csv
    csv_formatter.save()
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\io\formats\csvs.py", line 248, in save
    self._save()
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\io\formats\csvs.py", line 253, in _save
    self._save_body()
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\io\formats\csvs.py", line 291, in _save_body
    self._save_chunk(start_i, end_i)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\io\formats\csvs.py", line 298, in _save_chunk
    res = df._mgr.to_native_types(**self._number_format)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\core\internals\managers.py", line 679, in to_native_types
    return self.apply("to_native_types", **kwargs)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\core\internals\managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\pandas\core\internals\blocks.py", line 2110, in to_native_types
    values[mask] = na_rep
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py", line 2061, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\site-packages\IPython\core\ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\inspect.py", line 1541, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "c:\users\xoxix\appdata\local\programs\python\python39\lib\inspect.py", line 1499, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)

KeyboardInterrupt

## Taking a look at the dataframe
The next notebook will deal more with the topic of data visualisation and exploring the data set, but for now you can
visualize (part of) your dataframe by using the following commands:

In [5]:
# Show first N (e.g. 10) rows of the dataframe
data.head(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
3009,ARG,South America,Argentina,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,18933.907,0.6,191.032,5.50,16.2,27.7,NaN,5.00,76.67,0.845
48722,MEX,North America,Mexico,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,17336.469,2.5,152.783,13.06,6.9,21.4,87.847,1.38,75.05,0.779
48723,MEX,North America,Mexico,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,...,17336.469,2.5,152.783,13.06,6.9,21.4,87.847,1.38,75.05,0.779
3010,ARG,South America,Argentina,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,...,18933.907,0.6,191.032,5.50,16.2,27.7,NaN,5.00,76.67,0.845
3011,ARG,South America,Argentina,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,...,18933.907,0.6,191.032,5.50,16.2,27.7,NaN,5.00,76.67,0.845
48724,MEX,North America,Mexico,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,...,17336.469,2.5,152.783,13.06,6.9,21.4,87.847,1.38,75.05,0.779
3012,ARG,South America,Argentina,2020-01-04,NaN,NaN,NaN,NaN,NaN,NaN,...,18933.907,0.6,191.032,5.50,16.2,27.7,NaN,5.00,76.67,0.845
75171,THA,Asia,Thailand,2020-01-04,NaN,NaN,NaN,NaN,NaN,NaN,...,16277.671,0.1,109.861,7.04,1.9,38.8,90.670,2.10,77.15,0.777
48725,MEX,North America,Mexico,2020-01-04,NaN,NaN,NaN,NaN,NaN,NaN,...,17336.469,2.5,152.783,13.06,6.9,21.4,87.847,1.38,75.05,0.779
75172,THA,Asia,Thailand,2020-01-05,NaN,NaN,NaN,NaN,NaN,NaN,...,16277.671,0.1,109.861,7.04,1.9,38.8,90.670,2.10,77.15,0.777

In [11]:
# Tail will show the last N results of the dataframe.
data.tail(10)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
46479,MYS,Asia,Malaysia,2021-04-24,390252.0,2717.0,2484.714,1426.0,11.0,8.000,...,26808.164,0.1,260.942,16.74,1.0,42.4,NaN,1.9,76.16,0.810
41871,LAO,Asia,Laos,2021-04-24,247.0,88.0,27.000,NaN,NaN,0.000,...,6397.360,22.7,368.111,4.00,7.3,51.2,49.839,1.5,67.92,0.613
59539,PRY,South America,Paraguay,2021-04-24,265296.0,2162.0,2418.857,5802.0,87.0,78.714,...,8827.010,1.7,199.128,8.27,5.0,21.6,79.602,1.3,74.25,0.728
3935,ABW,North America,Aruba,2021-04-24,NaN,NaN,NaN,NaN,NaN,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
57045,OWID_OCE,NaN,Oceania,2021-04-24,42985.0,276.0,203.571,1041.0,3.0,3.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75170,TZA,Africa,Tanzania,2021-04-24,509.0,0.0,0.000,21.0,0.0,0.000,...,2683.304,49.1,217.288,5.75,3.3,26.7,47.953,0.7,65.46,0.529
28257,GAB,Africa,Gabon,2021-04-24,22433.0,0.0,82.143,138.0,0.0,0.714,...,16562.413,3.4,259.967,7.20,NaN,NaN,NaN,6.3,66.47,0.703
80366,URY,South America,Uruguay,2021-04-24,182326.0,2789.0,2846.571,2283.0,56.0,62.143,...,20551.409,0.1,160.708,6.93,14.0,19.9,NaN,2.8,77.91,0.817
21298,DJI,Africa,Djibouti,2021-04-24,10746.0,8.0,47.714,132.0,0.0,2.571,...,2705.406,22.5,258.037,6.05,1.7,24.5,NaN,1.4,67.11,0.524
83861,ZWE,Africa,Zimbabwe,2021-04-24,38064.0,19.0,52.143,1556.0,0.0,0.571,...,1899.775,21.4,307.846,1.82,1.6,30.7,36.791,1.7,61.49,0.571

In [76]:
from linearmodels import PanelOLS
regression = PanelOLS(timeData["new_cases"], timeData[["total_cases","diabetes_prevalence"]], time_effects=True)
print(regression.fit())

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              new_cases   R-squared:                        0.8155
Estimator:                   PanelOLS   R-squared (Between):              0.9619
No. Observations:               76599   R-squared (Within):               0.5743
Date:                Fri, Jun 18 2021   R-squared (Overall):              0.8162
Time:                        20:33:00   Log-likelihood                -8.386e+05
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.682e+05
Entities:                         187   P-value                           0.0000
Avg Obs:                       409.62   Distribution:                 F(2,76138)
Min Obs:                       94.000
Max Obs:                       459.00   F-statistic (robust):          1.682e+05
                                        P-value                           0.0000
Time periods:                     459   Distribution:                 F(2,76138)
Avg Obs:                       166.88
Min Obs:                       1.0000
Max Obs:                       187.00

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
total_cases             0.0057  9.745e-06     579.88     0.0000      0.0056      0.0057
diabetes_prevalence     28.740     12.567     2.2869     0.0222      4.1082      53.372
=======================================================================================

F-test for Poolability: 2.3075
P-value: 0.0000
Distribution: F(458,76138)

Included effects: Time